name: Deploy to Render

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch
  schedule:
    - cron: '*/10 * * * *'  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Write the Firebase service account key to a file
      - name: Write Firebase service account key
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > ${{GOOGLE_APPLICATION_CREDENTIALS}}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests (optional)
      - name: Run tests
        run: |
          # Add your test command here, e.g.:
          # python -m pytest

      # Deploy to Render
      - name: Deploy to Render
        uses: render-actions/deploy@v1
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}