services:
  - type: web
    name: text-submission-app
    env: python
    buildCommand: |
      echo "${FIREBASE_SERVICE_ACCOUNT}" > text-submission-firebase-adminsdk-fbsvc-37bd11c579.json
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        fromSecret: FIREBASE_SERVICE_ACCOUNT
      - key: GOOGLE_CLIENT_ID
        fromSecret: GOOGLE_CLIENT_ID
      - key: GOOGLE_CLIENT_SECRET
        fromSecret: GOOGLE_CLIENT_SECRET
      - key: GOOGLE_REDIRECT_URI
        value: https://grc-project.onrender.com/callback




