services:
  - type: web
    name: text-submission-app
    env: python
    buildCommand: |
      echo "${FIREBASE_SERVICE_ACCOUNT}" > ${GOOGLE_APPLICATION_CREDENTIALS}
       pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        fromSecret: FIREBASE_SERVICE_ACCOUNT
      - key: GOOGLE_CLIENT_ID
        fromSecret: GOOGLE_CLIENT_ID
      - key: GOOGLE_CLIENT_SECRET
        fromSecret: GOOGLE_CLIENT_SECRET
      - key: GOOGLE_REDIRECT_URI
        value: https://grc-project.onrender.com/callback
      - key: PUBLIC_KEY
        fromSecret: PUBLIC_KEY
      - key: GOOGLE_APPLICATION_CREDENTIALS
        fromSecret: GOOGLE_APPLICATION_CREDENTIALS